# -*- coding: utf-8 -*-
"""DAY-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6-MknR_tiF7P9B62dMUeRsF4ypff1e9

# Write a Python program to calculate the sum of all even numbers between 1 and a given positive integer n
"""

#Using exception handling in python
def sum_of_evens(n):
    if n < 1:
        return "Please enter a positive integer."
    total = sum(i for i in range(2, n + 1, 2))
    return total
try:
    n = int(input("Enter a positive integer: "))
    result = sum_of_evens(n)
    print(f"The sum of all even numbers between 1 and {n} is: {result}")
except ValueError:
    print("Invalid input! Please enter a valid positive integer.")