# -*- coding: utf-8 -*-
"""py_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4iHIFM1TQZFPC3udIJ6vT40u8wEbC2T

# Lists
"""

import numpy

list = [1.6, 'abc',4]
print(list)

#unordered list
list = [10, 30, 20, 40]
print(list)

"""# list operations

**Concatenation**
"""

a = [1, 2, 3]
b = [5, 6, 7]
c = a + b
print(c)

"""**repeatation**"""

a = [0] * 5
print(a)

"""**slicing**"""

a = [1,2,3,4,5,6,7]
print(a[1:3])
print(a[-4:-2])
print(a[-1:-3])
print(a[:5])
print(a[4:])
print(a[:])
print(a)

"""**assignement**"""

age = [18, 19, 20, 16]
hrs_studied = [5, 6, 4, 3.5]
marks =

"""**list cloning**"""

a = [1, 'vivek', 2, 'hari']
b = a[:]
print(b)

"""# data types in py
# 6/1/25
"""

#int
my_int = 42
print("Original Integer: ", my_int)

#list
my_list = [1, 'hello', 3.14, True]
print("Original List: ", my_list)
my_list.append('world')
print("List after appending: ", my_list)
my_list.remove(3.14)
print("List after removing: ", my_list)

#Tuple
my_tuple = (1, 'apple', 3.14, False)
print("Original Tuple: ", my_tuple)
print("Tuple length: ", len(my_tuple))
print("First element of the tuple: ", my_tuple[0])
print("Last element of the tuple: ", my_tuple[-1])

#for loop
for i in range(1,6):
    print(i)

#while loop
i = 1
while i <= 5:
    print(i)
    i += 1111111112

#if condition
number = int(input("Enter a number: "))
if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

#function
def greet(name):
    print("Hello, " + name + "!")
greet("VIVEK")

